name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Staging Environment
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 18
      - run: npm i
      - run: npm test
        env:
          AT_APP_API_KEY: ${{secrets.AT_APP_API_KEY}}
          AT_APP_USERNAME: ${{secrets.AT_APP_USERNAME}}
          TEST_PHONENUMBER: ${{secrets.TEST_PHONENUMBER}}